# Generated by Django 5.1.4 on 2024-12-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("goal_frequency", models.IntegerField()),
                (
                    "goal_unit",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal to"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal to"),
                            ("equal", "Equal to"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
