# Generated by Django 5.1.4 on 2024-12-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
