# Generated by Django 5.1.4 on 2025-01-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_habit_goal_unit_habit_goal_timespan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="goal_frequency",
            new_name="goalFrequency",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="goal_timespan",
            new_name="goalTimespan",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="goal_type",
            new_name="goalType",
        ),
    ]
