# Generated by Django 5.1.4 on 2025-01-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_goal_frequency_habit_goalfrequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
