# Generated by Django 5.1.4 on 2025-01-03 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="goalFrom",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="goalTo",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="goalFrequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="goalTimespan",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="goalType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gt", "Greater than"),
                    ("gte", "Greater than or equal to"),
                    ("lt", "Less than"),
                    ("lte", "Less than or equal to"),
                    ("equal", "Equal to"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
