# Generated by Django 5.1.4 on 2025-01-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_habit_goalfrom_habit_goalto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["private", "status", "goalFrom", "goalTimespan"]},
        ),
        migrations.AlterField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[(0, "Active"), (1, "Paused"), (2, "Deleted")],
                default="active",
                max_length=10,
            ),
        ),
    ]
