# Generated by Django 5.1.4 on 2025-01-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_goalfrequency_habit_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="goalType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GT", "Greater than"),
                    ("GTE", "Greater than or equal to"),
                    ("LT", "Less than"),
                    ("LTE", "Less than or equal to"),
                    ("EQUAL", "Equal to"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
