enum Status {
  active
  paused
  deleted
}

enum GoalType {
  GT
  GTE
  LT
  LTE
  EQUAL
}

type Entry {
  id: ID!
  habit: Habit!
  date: String!
  rating: Int
  description: String
}

type Habit {
  id: ID!
  author: Int!
  name: String!
  description: String
  private: Boolean!
  status: Status!
  goal: Int
  goalTimespan: Int
  goalType: GoalType
  goalFrom: String
  goalTo: String
  entries(days: Int): [Entry!]!
}

type Query {
  habits(author: Int!): [Habit!]!
}
